export const categories = {
  map: 'Mapas',
  weapon: 'Armas',
  arc: 'Enemigos ARC',
  grenade: 'Granadas',
  blueprint: 'Planos',
  project: 'Proyectos',
  container: 'Contenedores',
} as const;
export const fieldNames: Record<string, string> = {
  Health: 'Vida declarada',
  'Primary Attack': 'Ataque principal',
  Abilities: 'Habilidades declaradas',
  'Headshot Multiplier': 'Multiplicador a la cabeza',
  Durability: 'Durabilidad declarada',
  Stability: 'Estabilidad',
  Agility: 'Agilidad',
  Stealth: 'Sigilo',
  Weight: 'Peso declarado',
  'Ammo Type': 'Munición',
  'Firing Mode': 'Modo de disparo',
  'ARC Armor Penetration': 'Penetración ARC',
  Damage: 'Daño declarado',
  'Fire Rate': 'Cadencia declarada',
  Range: 'Alcance declarado',
  'Magazine Size': 'Cargador',
  Radius: 'Radio del efecto',
  'Homing Range': 'Alcance de búsqueda',
  Duration: 'Duración',
  Delay: 'Retardo',
  'ARC Stun Duration': 'Aturdimiento ARC',
  'Raider Stun Duration': 'Aturdimiento Raider',
  'Stamina Drain': 'Consumo de resistencia',
};
